### ISSUE TITLE
Listing a branch content

### ISSUE THREAD

**Issue by radaniba** [RisingOak/stashy#15]
Hello there,

Is there any example of this API usage to list the content of a specific branch and get listing of files in each directory inside a branch ?

Thanks

**Comment by campos-ddc** [comment]
Something in the lines of:

```python
paths = stashyinstance.projects['myproject'].repos['myrepo'].browse(at='mybranch')
```

`browse` takes parameters `path='', at=None, type=False, blame='', noContent=''`, which are also documented in [Stash API docs](https://developer.atlassian.com/static/rest/stash/3.0.1/stash-rest.html#idp1106160)

**Comment by dwdking** [comment]
I put in code to pull diff information and list associated files within a pull request. Not quite what you need but might be work in the mean time or part of the code is in place.

I have a pull request open so maybe it will be merged or there is the fork I made.

**Comment by tonytamsf** [comment]
please re-opened if still needed.
