### ISSUE TITLE
How does pagination work?

### ISSUE THREAD

**Issue by theotherwhitemeat** [RisingOak/stashy#26]
Apologies in advance, this is a question vs. a software issue.

How does pagination work?  For example, if I'd like to see all the branches in a repo, I can make the following query, and it returns a dict with the first page of 25 results.  How do I get the rest?

> type(stashyinstance)
> class 'stashy.client.Stash'
> stashyinstance.projects['myproject'].repos['myrepo'].branches()
> {dict of results goes here}

How do I get subsequent result pages?

Edit:
Actually branches() is currently broken:

projects['projectname'].repos['myrepo'].branches()

In maybe_throw
File: "stashy/errors.py"
Source:
29 | def maybe_throw(response):
30 *| if not response.ok:
31 | if response.status_code == 404:
Arguments:
response:

File "stashy/errors.py", line 30, in maybe_throw
exceptions.AttributeError, 'generator' object has no attribute 'ok'

Pull request here should resolve it:
https://github.com/RisingOak/stashy/pull/27

**Comment by campos-ddc** [comment]
Looks like a bug. `tags()` only returns the first page:

```python
return self._client.get(self.url('/tags'), params=params)
```

Comparing to `branches()`, that properly returns an iterator that paginates:

```python
return self.paginate('/branches', params=params)
```

This should be an easy fix.

**Comment by ahharu** [comment]
just change it to

return self._client.paginate(self.url('/tags'), params=params)
