### ISSUE TITLE
Unable to retrieve commits

### ISSUE THREAD

**Issue by adeekshith** [RisingOak/stashy#37]
I am unable to retrieve commits. Can you please help me with this.
- I am using this example
  `list(stash.projects[PROJECT].repos[REPO].pull_requests.commits())`
  It returns this error: `AttributeError: 'PullRequests' object has no attribute 'commits'`
- I could not get this working too:
  `stash.projects[PROJECT].repos[REPO].commits()`

I actually want to retrieve all the commits in a repo. Can you please help me with this. Thank you.

**Comment by ahharu** [comment]
You can't use it without params

Less parameter option is

##### stash.projects[PROJECT].repos[REPO].commits('sha1key')

where sha1key will be the commit until you wanna list them , so if you want everything, just put the last commit sha1

**Comment by adeekshith** [comment]
Thank you. That works. Using a blank string in place of sha1key is also pulling all the commits.
`stash.projects[PROJECT].repos[REPO].commits('')`

Thanks again. That saved me a lot of time.
