### ISSUE TITLE
Add ability to create / delete tags

### ISSUE THREAD

**Issue by tylerdave** [RisingOak/stashy#41]
The ability to create / delete tags was added in Stash 3.7.1: [STASH-4128](https://jira.atlassian.com/browse/STASH-4128)

Documentation:
POST: https://developer.atlassian.com/static/rest/stash/latest/stash-scm-git-rest.html#idp7360
DELETE: https://developer.atlassian.com/static/rest/stash/latest/stash-scm-git-rest.html#idp27856

**Comment by tonytamsf** [comment]
please re-opened if still needed.
