### ISSUE TITLE
Add support to 'branch-utils' APIs

### ISSUE THREAD

**Issue by campos-ddc** [RisingOak/stashy#5]
Some new APIs used to work with branches have been introduced ([documented here](https://developer.atlassian.com/static/rest/stash/2.10.1/stash-branch-utils-rest.html]))

So far, only a few methods are available:
- List branches
- Delete a branch
- List branches that contain a ref

For some reason, they are in a separate namespace (**/rest/branch-utils/1.0** instead of **/rest/api/1.0**).

**Comment by tonytamsf** [comment]
please reopen if you still want this

**Comment by hconhegg** [comment]
This would be very useful @tonytamsf
I currently get 405 when attempting to delete a branch using the repos.delete_branch() because it uses branch-utils. Should i create a new issue?
