### ISSUE TITLE
Stashy isn't getting updated on PyPI

### ISSUE THREAD

**Issue by raphaelcastaneda** [RisingOak/stashy#62]
Stashy is a pretty handy way to interact with Stash, and I've been trying to use it as the basis for adding Stash support to https://github.com/guykisel/inline-plz. However, the version currently hosted on PyPI is very outdated, and does not contain recent bug fixes and improvements needed to make this work.

I would be quite grateful if you could update the PyPI hosted package.

**Comment by IanLee1521** [comment]
If you could also make sure to tag the commit that you release, that would be great too.

**Comment by gdubicki** [comment]
+1

**Comment by bitf115** [comment]
@cosmin We would be quite grateful if you could update the PyPI hosted package.

**Comment by tonytamsf** [comment]
Looks like there is no update on the pypi index, how are people getting around this? building their own module and pushing it?

**Comment by cosmin** [comment]
I pushed a new version to PyPI a couple of days ago so you should be able to get 0.3 from there.
