### ISSUE TITLE
HTTP 405 when getting keys for a user

### ISSUE THREAD

**Issue by gdubicki** [RisingOak/stashy#65]
I am trying to use the code added in https://github.com/RisingOak/stashy/pull/33 (and later on add POST support to it - see https://github.com/grzegorz-dubicki/stashy/tree/more-ssh).

This code works:

```
print "%s" % self.bitbucket.ssh.list('gdubicki')
[{u'text': u'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAgEAyzlZRkspi4fTtxopqxApGymeZ3z16chlZmjEbjiYMNSPHztyf8dQmO7oPXrG+spDcBgMX3k4iLJzy/F7DFm91A4qd9xhKYeMBwYonGXtrNE(...)
```

..but when I am trying to use the `get` method directly then - perhaps because I don't know how to do it correctly - I get HTTP 405 errors:

```
print "%s" % self.bitbucket.ssh.get('gdubicki')
<Response [405]>
```

Am I doing it wrong or is it broken?

**Comment by grzegorz-dubicki** [comment]
Ok, I think that it was broken. After my fix in that PR the code above works for me.

**Comment by tonytamsf** [comment]
coolio closing https://github.com/RisingOak/stashy/issues/67 as well
