### ISSUE TITLE
Some user SSH public key-related methods seem not to work

### ISSUE THREAD

**Issue by gdubicki** [RisingOak/stashy#67]
(This is related to #65)

Either I don't know how to use that code or the following methods of `ssh.py` don't work:
### Keys.**getitem**

```
print "%s" % self.bitbucket.ssh[user]
```

returns:

```
(...)
TypeError: __init__() takes exactly 4 arguments (5 given)
```
### SshFilteredIterableResource.all and SshFilteredIterableResource.list

..with no username provided:

```
print "%s" % self.bitbucket.ssh.list()
```

and

```
for x in self.bitbucket.ssh.all():
        print "!!!%s" % x
```

..return empty list/no output, while the same with my username provided return my key.

**Comment by tonytamsf** [comment]
assuming it's a dup of https://github.com/RisingOak/stashy/issues/65
